[browser]
# 不用填
ua = ""

[account]
# 你的手机号对应你的密码，必须填，别忘记去掉”#“
# 177777777 = "密码"
# os.environ['ACCOUNTS']
env = [
"ACCOUNTS"
]

[cookies]

[message_push.Server_chan]
# server酱推送
send_key = os.environ['SERVER_KEY']

[message_push.Wechat_message]
# 微信企业消息
corpid = os.environ['WM_pid']
corpsecret = os.environ['WM_pst']
agentid = os.environ['WM_aid']

[message_push.Dingtalk_message]
# 钉钉推送
access_token = os.environ['DING_KEY']
